import { connectDB } from './db';
import Enquiry from '../models/Enquiry';
import otpService from '../services/otpService';
import emailService from '../services/emailService';
import whatsappService from '../services/whatsappService';

export function validateEnquiry(body){const errors={};if(!['popup','demo'].includes(body.formType))errors.formType="formType must be 'popup' or 'demo'";if(!body.name?.trim())errors.name='Name is required';if(!/^\d{10}$/.test((body.phone||'').replace(/\s/g,'')))errors.phone='Enter a valid 10-digit mobile number';if(!body.course?.trim())errors.course='Course is required';if(body.formType==='demo'&&body.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(body.email))errors.email='Enter a valid email address';return errors}
export async function submitEnquiry(body){await connectDB();const errors=validateEnquiry(body);if(Object.keys(errors).length)return{status:422,body:{success:false,errors}};if(!body.email)return{status:422,body:{success:false,message:'Email is required to receive OTP.'}};const enquiry=await Enquiry.create({formType:body.formType,name:body.name.trim(),phone:body.phone.replace(/\D/g,'').slice(-10),course:body.course.trim(),email:body.email.trim().toLowerCase(),message:body.message?.trim()||null,status:'pending_otp'});const otp=otpService.generateOTP();enquiry.otp=otpService.hashOTP(otp);enquiry.otpExpiry=otpService.expiryDate();await enquiry.save();await emailService.sendOTPEmail({to:enquiry.email,name:enquiry.name,otp,expiryMinutes:parseInt(process.env.OTP_EXPIRY_MINUTES)||10}).catch(()=>{});return{status:201,body:{success:true,enquiryId:enquiry._id,message:'OTP sent to your email. Please verify to complete.',...(process.env.NODE_ENV==='development'&&{__dev_otp:otp})}}}
export async function resendOTP({enquiryId}){await connectDB();if(!enquiryId)return{status:422,body:{success:false,message:'enquiryId required'}};const e=await Enquiry.findById(enquiryId);if(!e)return{status:404,body:{success:false,message:'Enquiry not found'}};if(e.otpVerified)return{status:400,body:{success:false,message:'Already verified'}};const cooldown=2*60*1000;if(e.otpExpiry&&e.otpExpiry-Date.now()>(parseInt(process.env.OTP_EXPIRY_MINUTES||10)*60000-cooldown))return{status:429,body:{success:false,message:'Please wait 2 minutes before requesting a new OTP'}};const otp=otpService.generateOTP();e.otp=otpService.hashOTP(otp);e.otpExpiry=otpService.expiryDate();await e.save();await emailService.sendOTPEmail({to:e.email,name:e.name,otp,expiryMinutes:parseInt(process.env.OTP_EXPIRY_MINUTES)||10}).catch(()=>{});return{status:200,body:{success:true,message:'New OTP sent to your email.',...(process.env.NODE_ENV==='development'&&{__dev_otp:otp})}}}
export async function verifyEnquiryOTP({enquiryId,otp}){await connectDB();if(!enquiryId||!/^\d{6}$/.test(otp||''))return{status:422,body:{success:false,message:'Valid enquiryId and 6-digit OTP are required'}};const e=await Enquiry.findById(enquiryId);if(!e)return{status:404,body:{success:false,message:'Enquiry not found'}};if(e.otpVerified)return{status:400,body:{success:false,message:'Already verified'}};if(!e.otpExpiry||Date.now()>new Date(e.otpExpiry).getTime()){e.status='failed';await e.save();return{status:400,body:{success:false,message:'OTP expired. Please request a new one.'}}};let valid=false;try{valid=otpService.verifyOTP(otp,e.otp)}catch{}if(!valid)return{status:400,body:{success:false,message:'Invalid OTP. Please try again.'}};e.otpVerified=true;e.status='verified';e.otp=null;e.otpExpiry=null;await e.save();const results=await Promise.allSettled([whatsappService.sendOwnerWhatsApp(e),emailService.sendOwnerNotificationEmail(e),whatsappService.sendStudentWhatsApp(e),emailService.sendStudentConfirmationEmail(e)]);e.notified={ownerWhatsApp:results[0].status==='fulfilled'&&results[0].value?.success!==false,ownerEmail:results[1].status==='fulfilled',studentWhatsApp:results[2].status==='fulfilled'&&results[2].value?.success!==false,studentEmail:results[3].status==='fulfilled'};await e.save();return{status:200,body:{success:true,message:'Verified! Our counsellor will contact you within 24 hours.',notifications:e.notified}}}
